name: flutter_edubridge
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dashboard/history.png
    - assets/dashboard/lessons.png
    - assets/dashboard/quizzes.png
    - assets/dashboard/ecology.jpg
    - assets/profile/user.png
    - assets/login_registration/bg-pic.png
    - assets/login_registration/logo.png
    - assets/subjects/reading.png
    - assets/subjects/spelling.png
    - assets/subjects/writing.png
